In [1]:
from matplotlib import pyplot
import pandas as pd
import numpy as np

In [26]:
fund = pd.read_csv('new_fund1.csv', thousands=',')
fund1 = fund.rename(columns={'Income Distributed' : 'Income_Distributed', 'Fund Size': 'Fund_Size'})
fund1

,Month,Year,Sales,Redemption,Net,Income_Distributed,Fund_Size,Dividend,FBMKLCI
0,Jan,1992,3.755638e+08,-5.403470e+08,-1.647832e+08,1.035420e+09,1.031930e+10,12.5,570.64
1,Feb,1992,4.194861e+08,-3.846571e+08,3.482893e+07,NaN,1.035413e+10,NaN,605.06
2,Mar,1992,3.804028e+08,-5.538938e+08,-1.734910e+08,NaN,1.018064e+10,NaN,593.21
3,Apr,1992,3.179610e+08,-2.151399e+08,1.028211e+08,NaN,1.028346e+10,NaN,591.63
4,May,1992,4.158162e+08,-2.657969e+08,1.500193e+08,NaN,1.043348e+10,NaN,589.09
5,Jun,1992,3.081471e+08,-2.355371e+08,7.261008e+07,NaN,1.050609e+10,NaN,592.33
6,Jul,1992,3.823834e+08,-2.317823e+08,1.506011e+08,NaN,1.065669e+10,NaN,601.53
7,Aug,1992,3.864552e+08,-2.183212e+08,1.681341e+08,NaN,1.082483e+10,NaN,569.68
8,Sep,1992,3.724761e+08,-2.063384e+08,1.661377e+08,NaN,1.099096e+10,NaN,602.28
9,Oct,1992,3.395863e+08,-2.836514e+08,5.593488e+07,NaN,1.104690e+10,NaN,641.31
10,Nov,1992,3.626499e+08,-1.990001e+08,1.636499e+08,NaN,1.121055e+10,NaN,641.89
11,Dec,1992,2.840091e+08,-8.521315e+07,1.987960e+08,NaN,1.140935e+10,NaN,643.96
12,Jan,1993,3.742650e+08,-6.026765e+08,-2.284115e+08,1.255813e+09,1.243675e+10,12.5,624.49
13,Feb,1993,3.646479e+08,-3.777424e+08,-1.309450e+07,NaN,1.242365e+10,NaN,638.19
14,Mar,1993,3.526084e+08,-3.551241e+08,-2.515794e+06,NaN,1.242114e+10,NaN,643.25
15,Apr,1993,3.804254e+08,-3.606310e+08,1.979439e+07,NaN,1.244093e+10,NaN,719.61
16,May,1993,3.692161e+08,-3.333473e+08,3.586883e+07,NaN,1.247680e+10,NaN,735.25
17,Jun,1993,3.695110e+08,-3.203064e+08,4.920463e+07,NaN,1.252600e+10,NaN,721.17
18,Jul,1993,4.619817e+08,-2.895515e+08,1.724303e+08,NaN,1.269843e+10,NaN,766.08
19,Aug,1993,3.999981e+08,-2.806652e+08,1.193329e+08,NaN,1.281777e+10,NaN,808.49
20,Sep,1993,4.541860e+08,-3.184750e+08,1.357110e+08,NaN,1.295348e+10,NaN,853.83
21,Oct,1993,4.504028e+08,-3.046179e+08,1.457849e+08,NaN,1.309926e+10,NaN,971.99
22,Nov,1993,4.434032e+08,-2.616082e+08,1.817950e+08,NaN,1.328106e+10,NaN,972.10
23,Dec,1993,2.972180e+08,-1.181772e+08,1.790408e+08,NaN,1.346010e+10,NaN,1275.32
24,Jan,1994,4.987059e+08,-1.278963e+09,-7.802575e+08,1.594868e+09,1.427471e+10,13.5,1106.99
25,Feb,1994,5.910855e+08,-6.857155e+08,-9.462998e+07,NaN,1.418008e+10,NaN,1125.63
26,Mar,1994,7.570134e+08,-3.948112e+08,3.622021e+08,NaN,1.454228e+10,NaN,952.72
27,Apr,1994,6.638617e+08,-4.247473e+08,2.391144e+08,NaN,1.478140e+10,NaN,1054.50
28,May,1994,4.858358e+08,-3.649428e+08,1.208930e+08,NaN,1.490229e+10,NaN,993.73
29,Jun,1994,5.473560e+08,-3.394341e+08,2.079219e+08,NaN,1.511021e+10,NaN,1011.58
...,...,...,...,...,...,...,...,...,...
318,Jul,2018,3.071425e+09,-3.820758e+09,-7.493329e+08,NaN,1.512092e+11,NaN,NaN
319,Aug,2018,2.746050e+09,-3.113242e+09,-3.671919e+08,NaN,1.508420e+11,NaN,NaN
320,Sep,2018,2.769328e+09,-3.157237e+09,-3.879093e+08,NaN,1.504541e+11,NaN,NaN
321,Oct,2018,3.380825e+09,-3.063806e+09,3.170189e+08,NaN,1.507711e+11,NaN,NaN
322,Nov,2018,2.956262e+09,-2.779564e+09,1.766985e+08,NaN,1.509478e+11,NaN,NaN
323,Dec,2018,1.867398e+09,-1.254852e+09,6.125459e+08,NaN,1.515603e+11,NaN,NaN
324,Jan,2019,4.396106e+09,-8.034729e+09,-3.638622e+09,1.060922e+10,1.585309e+11,7.0,NaN
325,Feb,2019,3.617660e+09,-4.578687e+09,-9.610267e+08,NaN,1.575699e+11,NaN,NaN
326,Mar,2019,3.630996e+09,-4.453109e+09,-8.221135e+08,NaN,1.567478e+11,NaN,NaN
327,Apr,2019,3.391870e+09,-4.195587e+09,-8.037169e+08,NaN,1.559441e+11,NaN,NaN
328,May,2019,3.000071e+09,-4.134833e+09,-1.134762e+09,NaN,1.548093e+11,NaN,NaN
329,Jun,2019,2.856877e+09,-3.916669e+09,-1.059792e+09,NaN,1.537495e+11,NaN,NaN
330,Jul,2019,3.192049e+09,-4.103615e+09,-9.115663e+08,NaN,1.528380e+11,NaN,NaN
331,Aug,2019,2.853544e+09,-3.342308e+09,-4.887636e+08,NaN,1.523492e+11,NaN,NaN
332,Sep,2019,2.877381e+09,-3.388124e+09,-5.107437e+08,NaN,1.518385e+11,NaN,NaN
333,Oct,2019,3.512310e+09,-3.286504e+09,2.258060e+08,NaN,1.520643e+11,NaN,NaN
334,Nov,2019,3.070863e+09,-2.980384e+09,9.047931e+07,NaN,1.521547e+11,NaN,NaN
335,Dec,2019,1.939556e+09,-1.344971e+09,5.945845e+08,NaN,1.527493e+11,NaN,NaN
336,Jan,2020,4.565430e+09,-8.608323e+09,-4.042892e+09,1.069245e+10,1.593989e+11,7.0,NaN
337,Feb,2020,3.756555e+09,-4.903623e+09,-1.147068e+09,NaN,1.582518e+11,NaN,NaN
338,Mar,2020,3.769958e+09,-4.767276e+09,-9.973177e+08,NaN,1.572545e+11,NaN,NaN
339,Apr,2020,3.521268e+09,-4.489855e+09,-9.685872e+08,NaN,1.562859e+11,NaN,NaN
340,May,2020,3.114159e+09,-4.423155e+09,-1.308996e+09,NaN,1.549769e+11,NaN,NaN
341,Jun,2020,2.965177e+09,-4.188201e+09,-1.223024e+09,NaN,1.537539e+11,NaN,NaN
342,Jul,2020,3.312674e+09,-4.386473e+09,-1.073800e+09,NaN,1.526801e+11,NaN,NaN
343,Aug,2020,2.961038e+09,-3.571374e+09,-6.103354e+08,NaN,1.520698e+11,NaN,NaN
344,Sep,2020,2.985433e+09,-3.619012e+09,-6.335781e+08,NaN,1.514362e+11,NaN,NaN
345,Oct,2020,3.643795e+09,-3.509202e+09,1.345930e+08,NaN,1.515708e+11,NaN,NaN
346,Nov,2020,3.185465e+09,-3.181205e+09,4.260152e+06,NaN,1.515750e+11,NaN,NaN
347,Dec,2020,2.011714e+09,-1.435090e+09,5.766232e+08,NaN,1.521517e+11,NaN,NaN

In [27]:
new_fund1 = fund1[fund1.Month == "Dec"]
new_fund1

,Month,Year,Sales,Redemption,Net,Income_Distributed,Fund_Size,Dividend,FBMKLCI
11,Dec,1992,2.840091e+08,-8.521315e+07,1.987960e+08,NaN,1.140935e+10,NaN,643.96
23,Dec,1993,2.972180e+08,-1.181772e+08,1.790408e+08,NaN,1.346010e+10,NaN,1275.32
35,Dec,1994,4.051568e+08,-1.323372e+08,2.728197e+08,NaN,1.726686e+10,NaN,971.21
47,Dec,1995,3.047351e+08,-1.569627e+08,1.477724e+08,NaN,2.063020e+10,NaN,995.17
59,Dec,1996,9.670216e+08,-1.887596e+08,7.782620e+08,NaN,2.505580e+10,NaN,1237.96
71,Dec,1997,6.900037e+08,-7.224989e+08,-3.249526e+07,NaN,2.898545e+10,NaN,594.44
83,Dec,1998,2.032709e+08,-2.838786e+08,-8.060771e+07,NaN,2.549286e+10,NaN,586.13
95,Dec,1999,3.401573e+08,-2.644537e+08,7.570354e+07,NaN,2.476887e+10,NaN,812.33
107,Dec,2000,3.054915e+08,-2.614703e+08,4.402125e+07,NaN,2.695900e+10,NaN,679.64
119,Dec,2001,3.685191e+08,-3.017816e+08,6.673752e+07,NaN,2.969176e+10,NaN,696.09
131,Dec,2002,3.457968e+08,-2.354716e+08,1.103252e+08,NaN,3.239333e+10,NaN,646.32
143,Dec,2003,4.636666e+08,-3.511599e+08,1.125068e+08,NaN,3.468254e+10,NaN,793.94
155,Dec,2004,5.101351e+08,-4.031103e+08,1.070248e+08,NaN,3.874537e+10,NaN,907.43
167,Dec,2005,7.509933e+08,-4.279180e+08,3.230753e+08,NaN,4.413332e+10,NaN,899.79
179,Dec,2006,5.506919e+08,-4.588127e+08,9.187917e+07,NaN,4.950623e+10,NaN,1096.24
191,Dec,2007,7.088364e+08,-4.815913e+08,2.272451e+08,NaN,5.520840e+10,NaN,1445.03
203,Dec,2008,7.760568e+08,-5.324993e+08,2.435575e+08,NaN,6.219447e+10,NaN,876.75
215,Dec,2009,1.094422e+09,-6.586536e+08,4.357687e+08,NaN,7.060989e+10,NaN,1272.78
227,Dec,2010,9.685894e+08,-6.607051e+08,3.078843e+08,NaN,8.272122e+10,NaN,1518.91
239,Dec,2011,1.450376e+09,-7.547045e+08,6.956718e+08,NaN,9.627676e+10,NaN,1530.73
251,Dec,2012,1.233427e+09,-6.174328e+08,6.159938e+08,NaN,1.102972e+11,NaN,1688.95
263,Dec,2013,1.822572e+09,-8.123910e+08,1.010181e+09,NaN,1.272650e+11,NaN,1882.20
275,Dec,2014,1.618048e+09,-8.453588e+08,7.726895e+08,NaN,1.372868e+11,NaN,1761.25
287,Dec,2015,1.218112e+09,-8.046086e+08,4.135035e+08,NaN,1.422415e+11,NaN,1692.51
299,Dec,2016,1.723082e+09,-1.074614e+09,6.484687e+08,NaN,1.442823e+11,NaN,NaN
311,Dec,2017,1.795240e+09,-1.164733e+09,6.305073e+08,NaN,1.487016e+11,NaN,NaN
323,Dec,2018,1.867398e+09,-1.254852e+09,6.125459e+08,NaN,1.515603e+11,NaN,NaN
335,Dec,2019,1.939556e+09,-1.344971e+09,5.945845e+08,NaN,1.527493e+11,NaN,NaN
347,Dec,2020,2.011714e+09,-1.435090e+09,5.766232e+08,NaN,1.521517e+11,NaN,NaN

In [33]:
pyplot.plot(new_fund1.Year, new_fund1.Fund_Size)
pyplot.show()

In [28]:
new_fund1["Fund1's Growth"] = new_fund1.Fund_Size/new_fund1.Fund_Size.shift(1)-1

S:\Program Files\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [31]:
new_fund1

,Month,Year,Sales,Redemption,Net,Income_Distributed,Fund_Size,Dividend,FBMKLCI,Fund1's Growth
11,Dec,1992,2.840091e+08,-8.521315e+07,1.987960e+08,NaN,1.140935e+10,NaN,643.96,NaN
23,Dec,1993,2.972180e+08,-1.181772e+08,1.790408e+08,NaN,1.346010e+10,NaN,1275.32,0.179743
35,Dec,1994,4.051568e+08,-1.323372e+08,2.728197e+08,NaN,1.726686e+10,NaN,971.21,0.282818
47,Dec,1995,3.047351e+08,-1.569627e+08,1.477724e+08,NaN,2.063020e+10,NaN,995.17,0.194786
59,Dec,1996,9.670216e+08,-1.887596e+08,7.782620e+08,NaN,2.505580e+10,NaN,1237.96,0.214520
71,Dec,1997,6.900037e+08,-7.224989e+08,-3.249526e+07,NaN,2.898545e+10,NaN,594.44,0.156836
83,Dec,1998,2.032709e+08,-2.838786e+08,-8.060771e+07,NaN,2.549286e+10,NaN,586.13,-0.120495
95,Dec,1999,3.401573e+08,-2.644537e+08,7.570354e+07,NaN,2.476887e+10,NaN,812.33,-0.028400
107,Dec,2000,3.054915e+08,-2.614703e+08,4.402125e+07,NaN,2.695900e+10,NaN,679.64,0.088423
119,Dec,2001,3.685191e+08,-3.017816e+08,6.673752e+07,NaN,2.969176e+10,NaN,696.09,0.101367
131,Dec,2002,3.457968e+08,-2.354716e+08,1.103252e+08,NaN,3.239333e+10,NaN,646.32,0.090987
143,Dec,2003,4.636666e+08,-3.511599e+08,1.125068e+08,NaN,3.468254e+10,NaN,793.94,0.070669
155,Dec,2004,5.101351e+08,-4.031103e+08,1.070248e+08,NaN,3.874537e+10,NaN,907.43,0.117143
167,Dec,2005,7.509933e+08,-4.279180e+08,3.230753e+08,NaN,4.413332e+10,NaN,899.79,0.139060
179,Dec,2006,5.506919e+08,-4.588127e+08,9.187917e+07,NaN,4.950623e+10,NaN,1096.24,0.121743
191,Dec,2007,7.088364e+08,-4.815913e+08,2.272451e+08,NaN,5.520840e+10,NaN,1445.03,0.115181
203,Dec,2008,7.760568e+08,-5.324993e+08,2.435575e+08,NaN,6.219447e+10,NaN,876.75,0.126540
215,Dec,2009,1.094422e+09,-6.586536e+08,4.357687e+08,NaN,7.060989e+10,NaN,1272.78,0.135308
227,Dec,2010,9.685894e+08,-6.607051e+08,3.078843e+08,NaN,8.272122e+10,NaN,1518.91,0.171525
239,Dec,2011,1.450376e+09,-7.547045e+08,6.956718e+08,NaN,9.627676e+10,NaN,1530.73,0.163870
251,Dec,2012,1.233427e+09,-6.174328e+08,6.159938e+08,NaN,1.102972e+11,NaN,1688.95,0.145626
263,Dec,2013,1.822572e+09,-8.123910e+08,1.010181e+09,NaN,1.272650e+11,NaN,1882.20,0.153837
275,Dec,2014,1.618048e+09,-8.453588e+08,7.726895e+08,NaN,1.372868e+11,NaN,1761.25,0.078748
287,Dec,2015,1.218112e+09,-8.046086e+08,4.135035e+08,NaN,1.422415e+11,NaN,1692.51,0.036090
299,Dec,2016,1.723082e+09,-1.074614e+09,6.484687e+08,NaN,1.442823e+11,NaN,NaN,0.014348
311,Dec,2017,1.795240e+09,-1.164733e+09,6.305073e+08,NaN,1.487016e+11,NaN,NaN,0.030629
323,Dec,2018,1.867398e+09,-1.254852e+09,6.125459e+08,NaN,1.515603e+11,NaN,NaN,0.019225
335,Dec,2019,1.939556e+09,-1.344971e+09,5.945845e+08,NaN,1.527493e+11,NaN,NaN,0.007845
347,Dec,2020,2.011714e+09,-1.435090e+09,5.766232e+08,NaN,1.521517e+11,NaN,NaN,-0.003913

In [34]:
pyplot.plot(new_fund1.Year, new_fund1["Fund1's Growth"])
pyplot.show()

In [39]:
sales_score = pd.DataFrame({'R^2':[-3.96,-3.65,-4.03,-5.04,-3.83,-2.41,-0.13]}, 
                           index=['Linear','Decision Tree','Random Forest','Holt Inception','Holt 10y','Holt 5y', 'Holt 3y'])
sales_score

                 R^2
Linear         -3.96
Decision Tree  -3.65
Random Forest  -4.03
Holt Inception -5.04
Holt 10y       -3.83
Holt 5y        -2.41
Holt 3y        -0.13

In [51]:
sales_score.plot(kind='bar', title ="R^2 Score of Sales Predictors",figsize=(15,10),legend=False, fontsize=16)
pyplot.show()

In [56]:
red_score = pd.DataFrame({'R^2':[-1.80,-0.80,-0.72,0.86,0.92,0.91,0.79]}, 
                           index=['Linear','Decision Tree','Random Forest','Holt Inception','Holt 10y','Holt 5y', 'Holt 3y'])
red_score

                 R^2
Linear         -1.80
Decision Tree  -0.80
Random Forest  -0.72
Holt Inception  0.86
Holt 10y        0.92
Holt 5y         0.91
Holt 3y         0.79

In [57]:
red_score.plot(kind='bar', title ="R^2 Score of Redemptions Predictors",figsize=(15,10),legend=False, fontsize=16)
pyplot.show()